export const LIMITATION_OF_LIABILITY = {
  id: 'limitation_of_liability',
  title: {
    es: 'Limitación de Responsabilidad',
    en: 'Limitation of Liability'
  },
  descriptions: [
    {
      es: 'EL SITIO WEB Y SU CONTENIDO SE PROPORCIONAN "TAL CUAL", Y NO SE APLICAN A ESTE SITIO WEB GARANTÍAS EXPRESAS O IMPLÍCITAS, INCLUIDAS, PERO SIN LIMITARSE A ELLAS, LAS DE COMERCIABILIDAD O IDONEIDAD PARA UN FIN DETERMINADO. NO SE GARANTIZA QUE EL USO DE ESTE SITIO WEB SEA ININTERRUMPIDO, SIN ERRORES, O QUE ESTÉ PROTEGIDO DE VIRUS U OTROS CÓDIGOS DAÑINOS. NO SE GARANTIZA LA EXACTITUD, IDONEIDAD, ADECUACIÓN, FIABILIDAD, PUNTUALIDAD O INTEGRIDAD DE LA INFORMACIÓN Y EL MATERIAL CONTENIDOS EN ESTE SITIO WEB, Y SE RECHAZA EXPRESAMENTE CUALQUIER RESPONSABILIDAD DERIVADA DE ELLO. EN NINGUNA CIRCUNSTANCIA Promo Example, INC. O CUALQUIERA DE SUS FUNCIONARIOS SERÁ RESPONSABLE DE CUALQUIER DAÑO DIRECTO, INDIRECTO, INCIDENTAL, CONSECUENTE, PUNITIVO O EJEMPLAR QUE SURJA DE CUALQUIER USO O INCAPACIDAD DE USAR ESTE SITIO WEB.',
      en: 'THE WEBSITE AND THE CONTENTS CONTAINED HEREIN ARE PROVIDED “AS IS,” AND NO EXPRESS OR IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, APPLY TO THIS WEBSITE. THERE ARE NO WARRANTIES THAT THE USE OF THIS WEBSITE SHALL BE UNINTERRUPTED, WITHOUT ERRORS, OR PROTECTED FROM VIRUSES OR OTHER HARMFUL CODE. THERE ARE NO WARRANTIES CONCERNING THE ACCURACY, SUITABILITY, ADEQUACY, RELIABILITY, TIMELINESS, OR COMPLETENESS OF THE INFORMATION AND MATERIAL CONTAINED ON THIS WEBSITE, AND ANY SUCH LIABILITY RESULTING THEREFROM IS EXPRESSLY DISCLAIMED. UNDER NO CIRCUMSTANCES WILL Promo Example, INC. OR ANY OF ITS OFFICERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES ARISING OUT OF ANY USE OR INABILITY TO USE THIS WEBSITE.'
    },
  ]
}